In [1]:
!pip install pandas
!pip install numpy
!pip install nltk
!pip install scikit-learn
!pip install tensorflow

Requirement already satisfied: pandas in g:\himaml\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in g:\himaml\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in g:\himaml\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in g:\himaml\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in g:\himaml\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in g:\himaml\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in g:\himaml\lib\site-packages (2.3.5)
Requirement already satisfied: nltk in g:\himaml\lib\site-packages (3.9.2)
Requirement already satisfied: click in g:\himaml\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in g:\himaml\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in g:\himaml\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in g:\himaml\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in g:\himaml\lib\site-packages (from click->nltk) (0.4.6)
Requirement already satisfied: scikit-learn in g:\himaml\lib\site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in g:\himaml\lib\site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in g:\himaml\lib\site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in g:\himaml\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in g:\himaml\lib\site-packages (from scikit-learn) (3.5.0)
Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Downloading opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in g:\himaml\lib\site-packages (from tensorflow) (25.0)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in g:\himaml\lib\site-packages (from tensorflow) (2.32.5)
Requirement already satisfied: setuptools in g:\himaml\lib\site-packages (from tensorflow) (80.9.0)
Requirement already satisfied: six>=1.12.0 in g:\himaml\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in g:\himaml\lib\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in g:\himaml\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.82.1-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.15.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in g:\himaml\lib\site-packages (from tensorflow) (2.3.5)
Collecting h5py<3.15.0,>=3.11.0 (from tensorflow)
  Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl.metadata (2.7 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in g:\himaml\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in g:\himaml\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in g:\himaml\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in g:\himaml\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.11.12)
Requirement already satisfied: wheel<1.0,>=0.23.0 in g:\himaml\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in g:\himaml\lib\site-packages (from keras>=3.12.0->tensorflow) (14.2.0)
Collecting namex (from keras>=3.12.0->tensorflow)
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp313-cp313-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in g:\himaml\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in g:\himaml\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in g:\himaml\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 2.9/351.2 MB 15.3 MB/s eta 0:00:23
    --------------------------------------- 6.0/351.2 MB 14.5 MB/s eta 0:00:24
    --------------------------------------- 8.4/351.2 MB 13.6 MB/s eta 0:00:26
   - -------------------------------------- 11.3/351.2 MB 13.3 MB/s eta 0:00:26
   - -------------------------------------- 13.9/351.2 MB 13.1 MB/s eta 0:00:26
   - -------------------------------------- 16.3/351.2 MB 12.9 MB/s eta 0:00:26
   -- ------------------------------------- 19.4/351.2 MB 13.3 MB/s eta 0:00:25
   -- ------------------------------------- 22.8/351.2 MB 13.6 MB/s eta 0:00:25
   -- ------------------------------------- 26.2/351.2 MB 13.9 MB/s eta 0:00:24
   --- ------------------------------------ 28.8/351.2 MB 13.7 MB/s eta 0:00:24
   --- ------------------------------------ 32.2/351.2 MB 14.0 MB/s eta 0:00:23
   ---- ----------------------------------- 35.7/351.2 MB 14.1 MB/s eta 0:00:23
   ---- ----------------------------------- 38.3/351.2 MB 14.0 MB/s eta 0:00:23
   ---- ----------------------------------- 41.4/351.2 MB 14.1 MB/s eta 0:00:22
   ----- ---------------------------------- 44.6/351.2 MB 14.2 MB/s eta 0:00:22
   ----- ---------------------------------- 46.7/351.2 MB 13.9 MB/s eta 0:00:22
   ----- ---------------------------------- 49.3/351.2 MB 13.8 MB/s eta 0:00:22
   ----- ---------------------------------- 52.2/351.2 MB 13.8 MB/s eta 0:00:22
   ------ --------------------------------- 53.7/351.2 MB 13.6 MB/s eta 0:00:22
   ------ --------------------------------- 54.5/351.2 MB 13.1 MB/s eta 0:00:23
   ------ --------------------------------- 56.9/351.2 MB 13.0 MB/s eta 0:00:23
   ------ --------------------------------- 59.2/351.2 MB 12.9 MB/s eta 0:00:23
   ------ --------------------------------- 61.3/351.2 MB 12.8 MB/s eta 0:00:23
   ------- -------------------------------- 63.2/351.2 MB 12.7 MB/s eta 0:00:23
   ------- -------------------------------- 65.5/351.2 MB 12.6 MB/s eta 0:00:23
   ------- -------------------------------- 67.9/351.2 MB 12.5 MB/s eta 0:00:23
   -------- ------------------------------- 70.3/351.2 MB 12.5 MB/s eta 0:00:23
   -------- ------------------------------- 72.4/351.2 MB 12.4 MB/s eta 0:00:23
   -------- ------------------------------- 74.7/351.2 MB 12.4 MB/s eta 0:00:23
   -------- ------------------------------- 76.8/351.2 MB 12.3 MB/s eta 0:00:23
   -------- ------------------------------- 78.1/351.2 MB 12.1 MB/s eta 0:00:23
   --------- ------------------------------ 79.4/351.2 MB 11.9 MB/s eta 0:00:23
   --------- ------------------------------ 81.5/351.2 MB 11.8 MB/s eta 0:00:23
   --------- ------------------------------ 83.4/351.2 MB 11.8 MB/s eta 0:00:23
   --------- ------------------------------ 85.5/351.2 MB 11.7 MB/s eta 0:00:23
   ---------- ----------------------------- 87.8/351.2 MB 11.7 MB/s eta 0:00:23
   ---------- ----------------------------- 89.9/351.2 MB 11.7 MB/s eta 0:00:23
   ---------- ----------------------------- 92.3/351.2 MB 11.7 MB/s eta 0:00:23
   ---------- ----------------------------- 94.6/351.2 MB 11.7 MB/s eta 0:00:22
   ----------- ---------------------------- 97.0/351.2 MB 11.7 MB/s eta 0:00:22
   ----------- ---------------------------- 99.1/351.2 MB 11.6 MB/s eta 0:00:22
   ----------- --------------------------- 101.2/351.2 MB 11.6 MB/s eta 0:00:22
   ----------- --------------------------- 103.8/351.2 MB 11.6 MB/s eta 0:00:22
   ----------- --------------------------- 106.2/351.2 MB 11.6 MB/s eta 0:00:22
   ----------- --------------------------- 108.0/351.2 MB 11.6 MB/s eta 0:00:22
   ------------ -------------------------- 109.8/351.2 MB 11.5 MB/s eta 0:00:21
   ------------ -------------------------- 110.9/351.2 MB 11.3 MB/s eta 0:00:22
   ------------ -------------------------- 113.0/351.2 MB 11.3 MB/s eta 0:00:22
   ------------ -------------------------- 114.8/351.2 MB 11.3 MB/s eta 0:00:21
   ------------ -------------------------- 116.9/351.2 MB 11.3 MB/s eta 0:00:21
   ------------- ------------------------- 119.5/351.2 MB 11.3 MB/s eta 0:00:21
   ------------- ------------------------- 121.1/351.2 MB 11.2 MB/s eta 0:00:21
   ------------- ------------------------- 123.7/351.2 MB 11.2 MB/s eta 0:00:21
   -------------- ------------------------ 126.4/351.2 MB 11.2 MB/s eta 0:00:21
   -------------- ------------------------ 128.5/351.2 MB 11.2 MB/s eta 0:00:20
   -------------- ------------------------ 130.8/351.2 MB 11.2 MB/s eta 0:00:20
   -------------- ------------------------ 133.4/351.2 MB 11.2 MB/s eta 0:00:20
   --------------- ----------------------- 135.3/351.2 MB 11.1 MB/s eta 0:00:20
   --------------- ----------------------- 135.8/351.2 MB 10.9 MB/s eta 0:00:20
   --------------- ----------------------- 137.9/351.2 MB 10.7 MB/s eta 0:00:20
   --------------- ----------------------- 139.7/351.2 MB 10.7 MB/s eta 0:00:20
   --------------- ----------------------- 142.1/351.2 MB 10.7 MB/s eta 0:00:20
   ---------------- ---------------------- 144.4/351.2 MB 10.7 MB/s eta 0:00:20
   ---------------- ---------------------- 146.5/351.2 MB 10.7 MB/s eta 0:00:20
   ---------------- ---------------------- 148.6/351.2 MB 10.7 MB/s eta 0:00:19
   ---------------- ---------------------- 151.0/351.2 MB 10.7 MB/s eta 0:00:19
   ----------------- --------------------- 153.9/351.2 MB 10.8 MB/s eta 0:00:19
   ----------------- --------------------- 156.5/351.2 MB 10.8 MB/s eta 0:00:19
   ----------------- --------------------- 159.6/351.2 MB 10.8 MB/s eta 0:00:18
   ------------------ -------------------- 162.8/351.2 MB 10.9 MB/s eta 0:00:18
   ------------------ -------------------- 166.2/351.2 MB 11.0 MB/s eta 0:00:17
   ------------------ -------------------- 168.8/351.2 MB 11.0 MB/s eta 0:00:17
   ------------------- ------------------- 172.5/351.2 MB 11.1 MB/s eta 0:00:17
   ------------------- ------------------- 175.6/351.2 MB 11.1 MB/s eta 0:00:16
   ------------------- ------------------- 178.8/351.2 MB 11.2 MB/s eta 0:00:16
   -------------------- ------------------ 181.9/351.2 MB 11.2 MB/s eta 0:00:16
   -------------------- ------------------ 184.8/351.2 MB 11.3 MB/s eta 0:00:15
   -------------------- ------------------ 187.7/351.2 MB 11.3 MB/s eta 0:00:15
   --------------------- ----------------- 190.8/351.2 MB 11.3 MB/s eta 0:00:15
   --------------------- ----------------- 194.0/351.2 MB 11.4 MB/s eta 0:00:14
   --------------------- ----------------- 197.1/351.2 MB 11.4 MB/s eta 0:00:14
   ---------------------- ---------------- 200.5/351.2 MB 11.5 MB/s eta 0:00:14
   ---------------------- ---------------- 203.9/351.2 MB 11.5 MB/s eta 0:00:13
   ---------------------- ---------------- 207.1/351.2 MB 11.6 MB/s eta 0:00:13
   ----------------------- --------------- 210.0/351.2 MB 11.6 MB/s eta 0:00:13
   ----------------------- --------------- 211.8/351.2 MB 11.6 MB/s eta 0:00:13
   ----------------------- --------------- 212.3/351.2 MB 11.3 MB/s eta 0:00:13
   ------------------------ -------------- 216.5/351.2 MB 11.4 MB/s eta 0:00:12
   ------------------------ -------------- 219.9/351.2 MB 11.4 MB/s eta 0:00:12
   ------------------------ -------------- 223.1/351.2 MB 11.5 MB/s eta 0:00:12
   ------------------------- ------------- 225.7/351.2 MB 11.5 MB/s eta 0:00:11
   ------------------------- ------------- 228.6/351.2 MB 11.5 MB/s eta 0:00:11
   ------------------------- ------------- 231.5/351.2 MB 11.5 MB/s eta 0:00:11
   ------------------------- ------------- 233.8/351.2 MB 11.5 MB/s eta 0:00:11
   -------------------------- ------------ 236.2/351.2 MB 11.5 MB/s eta 0:00:10
   -------------------------- ------------ 238.8/351.2 MB 11.5 MB/s eta 0:00:10
   -------------------------- ------------ 240.9/351.2 MB 11.5 MB/s eta 0:00:10
   --------------------------- ----------- 243.3/351.2 MB 11.5 MB/s eta 0:00:10
   --------------------------- ----------- 245.4/351.2 MB 11.5 MB/s eta 0:00:10
   --------------------------- ----------- 246.2/351.2 MB 11.5 MB/s eta 0:00:10
   --------------------------- ----------- 247.5/351.2 MB 11.4 MB/s eta 0:00:10
   --------------------------- ----------- 250.1/351.2 MB 11.4 MB/s eta 0:00:09
   ---------------------------- ---------- 252.7/351.2 MB 11.4 MB/s eta 0:00:09
   ---------------------------- ---------- 255.6/351.2 MB 11.4 MB/s eta 0:00:09
   ---------------------------- ---------- 258.7/351.2 MB 11.4 MB/s eta 0:00:09
   ----------------------------- --------- 261.9/351.2 MB 11.5 MB/s eta 0:00:08
   ----------------------------- --------- 264.8/351.2 MB 11.5 MB/s eta 0:00:08
   ----------------------------- --------- 267.1/351.2 MB 11.5 MB/s eta 0:00:08
   ------------------------------ -------- 270.3/351.2 MB 11.5 MB/s eta 0:00:08
   ------------------------------ -------- 273.4/351.2 MB 11.5 MB/s eta 0:00:07
   ------------------------------ -------- 276.3/351.2 MB 11.5 MB/s eta 0:00:07
   ------------------------------ -------- 277.9/351.2 MB 11.5 MB/s eta 0:00:07
   ------------------------------- ------- 281.3/351.2 MB 11.5 MB/s eta 0:00:07
   ------------------------------- ------- 284.2/351.2 MB 11.5 MB/s eta 0:00:06
   ------------------------------- ------- 286.3/351.2 MB 11.4 MB/s eta 0:00:06
   ------------------------------- ------- 287.8/351.2 MB 11.4 MB/s eta 0:00:06
   -------------------------------- ------ 288.6/351.2 MB 11.3 MB/s eta 0:00:06
   -------------------------------- ------ 291.0/351.2 MB 11.3 MB/s eta 0:00:06
   -------------------------------- ------ 293.3/351.2 MB 11.3 MB/s eta 0:00:06
   -------------------------------- ------ 295.7/351.2 MB 11.2 MB/s eta 0:00:05
   --------------------------------- ----- 298.3/351.2 MB 11.2 MB/s eta 0:00:05
   --------------------------------- ----- 300.4/351.2 MB 11.2 MB/s eta 0:00:05
   --------------------------------- ----- 302.8/351.2 MB 11.1 MB/s eta 0:00:05
   --------------------------------- ----- 305.4/351.2 MB 11.1 MB/s eta 0:00:05
   ---------------------------------- ---- 307.2/351.2 MB 11.1 MB/s eta 0:00:04
   ---------------------------------- ---- 309.9/351.2 MB 11.1 MB/s eta 0:00:04
   ---------------------------------- ---- 312.0/351.2 MB 11.1 MB/s eta 0:00:04
   ---------------------------------- ---- 315.1/351.2 MB 11.1 MB/s eta 0:00:04
   ----------------------------------- --- 318.0/351.2 MB 11.2 MB/s eta 0:00:03
   ----------------------------------- --- 319.8/351.2 MB 11.2 MB/s eta 0:00:03
   ----------------------------------- --- 320.6/351.2 MB 11.1 MB/s eta 0:00:03
   ----------------------------------- --- 321.7/351.2 MB 11.1 MB/s eta 0:00:03
   ------------------------------------ -- 324.5/351.2 MB 11.1 MB/s eta 0:00:03
   ------------------------------------ -- 327.7/351.2 MB 11.1 MB/s eta 0:00:03
   ------------------------------------ -- 330.0/351.2 MB 11.1 MB/s eta 0:00:02
   ------------------------------------ -- 332.7/351.2 MB 11.1 MB/s eta 0:00:02
   ------------------------------------- - 335.0/351.2 MB 11.1 MB/s eta 0:00:02
   ------------------------------------- - 337.4/351.2 MB 11.1 MB/s eta 0:00:02
   ------------------------------------- - 339.5/351.2 MB 11.2 MB/s eta 0:00:02
   ------------------------------------- - 341.8/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  343.9/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  346.3/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  348.7/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 11.2 MB/s eta 0:00:01
   ---------------------------------------- 351.2/351.2 MB 10.4 MB/s  0:00:32
Downloading grpcio-1.82.1-cp313-cp313-win_amd64.whl (5.0 MB)
   ---------------------------------------- 0.0/5.0 MB ? eta -:--:--
   ------------------------- -------------- 3.1/5.0 MB 15.7 MB/s eta 0:00:01
   ---------------------------------------  5.0/5.0 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 5.0/5.0 MB 10.3 MB/s  0:00:00
Downloading h5py-3.14.0-cp313-cp313-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ------------------------------------ --- 2.6/2.9 MB 14.0 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 11.0 MB/s  0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Downloading protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading absl_py-2.5.0-py3-none-any.whl (137 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Downloading flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.15.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 9.5 MB/s  0:00:00
Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Downloading opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Downloading namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.1-cp313-cp313-win_amd64.whl (343 kB)
Installing collected packages: namex, libclang, flatbuffers, termcolor, protobuf, optree, opt_einsum, ml_dtypes, h5py, grpcio, google_pasta, gast, astunparse, absl-py, keras, tensorflow

   ----------------------------------------  0/16 [namex]
   ----------------------------------------  0/16 [namex]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]
   -- -------------------------------------  1/16 [libclang]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.51.0 requires protobuf<7,>=3.20, but you have protobuf 7.35.1 which is incompatible.

In [1]:
# Reading JSON file
import json

# Data manipulation
import pandas as pd
import numpy as np

# Regular Expressions
import re

# Natural Language Toolkit
import nltk

# Tokenization
from nltk.tokenize import word_tokenize

# Lemmatization
from nltk.stem import WordNetLemmatizer

# TensorFlow Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer

# Padding sequences
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Encoding labels
from sklearn.preprocessing import LabelEncoder

# Saving tokenizer and encoder
import pickle

In [2]:
import nltk

nltk.download('punkt')
nltk.download('punkt_tab')   # For newer NLTK versions
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lakshmi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Lakshmi\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lakshmi\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\Lakshmi\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

True

In [3]:
#example to check if it is working or not
sentence = "What's the weather in Chennai today?"

tokens = word_tokenize(sentence)

print(tokens)

['What', "'s", 'the', 'weather', 'in', 'Chennai', 'today', '?']

In [4]:
#example to check if it is working or not
#because lemmatize() assumes every word is a noun unless you specify otherwise. so thats why ran -> ran
lemmatizer = WordNetLemmatizer()

words = ["running", "ran" ,"temperatures", "cars", "children"]

for word in words:
    print(word, "->", lemmatizer.lemmatize(word))
print(lemmatizer.lemmatize("running", pos="v"))

running -> running
ran -> ran
temperatures -> temperature
cars -> car
children -> child
run

In [5]:
# Load the intents.json file here .. means intent is in data dir so .. mean go back from note fold and enter data fold then intent

with open("../data/intents.json", "r") as file:
    intents = json.load(file)

In [6]:
print(intents.keys())
print(intents["intents"][0])
print(intents)

dict_keys(['intents'])
{'tag': 'greeting', 'patterns': ['hi', 'hello', 'hey', 'good morning', 'good evening', 'hey bot', 'hello chatbot', 'hi there', 'greetings', 'good afternoon'], 'responses': ['Hello!', 'Hi! How can I help?', 'Welcome!']}
{'intents': [{'tag': 'greeting', 'patterns': ['hi', 'hello', 'hey', 'good morning', 'good evening', 'hey bot', 'hello chatbot', 'hi there', 'greetings', 'good afternoon'], 'responses': ['Hello!', 'Hi! How can I help?', 'Welcome!']}, {'tag': 'goodbye', 'patterns': ['bye', 'goodbye', 'see you', 'take care', 'catch you later', 'bye bot', 'see you later'], 'responses': ['Goodbye!', 'See you soon!', 'Take care!']}, {'tag': 'thanks', 'patterns': ['thanks', 'thank you', 'thanks a lot', 'much appreciated', 'thank you so much', 'awesome thanks'], 'responses': ["You're welcome!", 'Happy to help!', 'Anytime!']}, {'tag': 'help', 'patterns': ['help', 'what can you do', 'show commands', 'how can you help', 'features', 'supported weather information'], 'responses': ['I can provide weather information for cities.']}, {'tag': 'bot_name', 'patterns': ['who are you', 'what is your name', 'your name', 'are you a chatbot', 'introduce yourself'], 'responses': ["I'm your Weather Chatbot."]}, {'tag': 'weather_overview', 'patterns': ['weather today', 'current weather', 'weather report', 'weather update', 'how is the weather', "today's weather", 'show weather', 'complete weather report', 'Weather in Delhi', 'Weather in Mumbai', 'Weather in Chennai', 'Weather in Hyderabad', 'Weather in Bengaluru', 'Weather in Kolkata', 'Weather in Visakhapatnam'], 'responses': ['Fetching complete weather details.', 'Checking the latest weather.']}, {'tag': 'current_temperature', 'patterns': ['What is the current temperature?', 'Show current temperature', 'Current current temperature', 'Tell me the current temperature', 'current temperature today', "Today's current temperature", 'Can you check the current temperature?', 'I need the current temperature', 'Give me the current temperature', 'Latest current temperature', 'Current temperature in Delhi', 'Current temperature in Mumbai', 'Current temperature in Chennai', 'Current temperature in Hyderabad', 'Current temperature in Bengaluru', 'Current temperature in Kolkata', 'Current temperature in Visakhapatnam'], 'responses': ['Checking the current temperature.', 'Fetching the current temperature.', 'Let me get the current temperature.']}, {'tag': 'feels_like_temperature', 'patterns': ['What is the feels like temperature?', 'Show feels like temperature', 'Current feels like temperature', 'Tell me the feels like temperature', 'feels like temperature today', "Today's feels like temperature", 'Can you check the feels like temperature?', 'I need the feels like temperature', 'Give me the feels like temperature', 'Latest feels like temperature', 'Feels like temperature in Delhi', 'Feels like temperature in Mumbai', 'Feels like temperature in Chennai', 'Feels like temperature in Hyderabad', 'Feels like temperature in Bengaluru', 'Feels like temperature in Kolkata', 'Feels like temperature in Visakhapatnam'], 'responses': ['Checking the feels like temperature.', 'Fetching the feels like temperature.', 'Let me get the feels like temperature.']}, {'tag': 'minimum_temperature', 'patterns': ['What is the minimum temperature?', 'Show minimum temperature', 'Current minimum temperature', 'Tell me the minimum temperature', 'minimum temperature today', "Today's minimum temperature", 'Can you check the minimum temperature?', 'I need the minimum temperature', 'Give me the minimum temperature', 'Latest minimum temperature', 'Minimum temperature in Delhi', 'Minimum temperature in Mumbai', 'Minimum temperature in Chennai', 'Minimum temperature in Hyderabad', 'Minimum temperature in Bengaluru', 'Minimum temperature in Kolkata', 'Minimum temperature in Visakhapatnam'], 'responses': ['Checking the minimum temperature.', 'Fetching the minimum temperature.', 'Let me get the minimum temperature.']}, {'tag': 'maximum_temperature', 'patterns': ['What is the maximum temperature?', 'Show maximum temperature', 'Current maximum temperature', 'Tell me the maximum temperature', 'maximum temperature today', "Today's maximum temperature", 'Can you check the maximum temperature?', 'I need the maximum temperature', 'Give me the maximum temperature', 'Latest maximum temperature', 'Maximum temperature in Delhi', 'Maximum temperature in Mumbai', 'Maximum temperature in Chennai', 'Maximum temperature in Hyderabad', 'Maximum temperature in Bengaluru', 'Maximum temperature in Kolkata', 'Maximum temperature in Visakhapatnam'], 'responses': ['Checking the maximum temperature.', 'Fetching the maximum temperature.', 'Let me get the maximum temperature.']}, {'tag': 'humidity', 'patterns': ['What is the humidity?', 'Show humidity', 'Current humidity', 'Tell me the humidity', 'humidity today', "Today's humidity", 'Can you check the humidity?', 'I need the humidity', 'Give me the humidity', 'Latest humidity', 'Humidity in Delhi', 'Humidity in Mumbai', 'Humidity in Chennai', 'Humidity in Hyderabad', 'Humidity in Bengaluru', 'Humidity in Kolkata', 'Humidity in Visakhapatnam'], 'responses': ['Checking the humidity.', 'Fetching the humidity.', 'Let me get the humidity.']}, {'tag': 'wind_speed', 'patterns': ['What is the wind speed?', 'Show wind speed', 'Current wind speed', 'Tell me the wind speed', 'wind speed today', "Today's wind speed", 'Can you check the wind speed?', 'I need the wind speed', 'Give me the wind speed', 'Latest wind speed', 'Wind speed in Delhi', 'Wind speed in Mumbai', 'Wind speed in Chennai', 'Wind speed in Hyderabad', 'Wind speed in Bengaluru', 'Wind speed in Kolkata', 'Wind speed in Visakhapatnam'], 'responses': ['Checking the wind speed.', 'Fetching the wind speed.', 'Let me get the wind speed.']}, {'tag': 'wind_direction', 'patterns': ['What is the wind direction?', 'Show wind direction', 'Current wind direction', 'Tell me the wind direction', 'wind direction today', "Today's wind direction", 'Can you check the wind direction?', 'I need the wind direction', 'Give me the wind direction', 'Latest wind direction', 'Wind direction in Delhi', 'Wind direction in Mumbai', 'Wind direction in Chennai', 'Wind direction in Hyderabad', 'Wind direction in Bengaluru', 'Wind direction in Kolkata', 'Wind direction in Visakhapatnam'], 'responses': ['Checking the wind direction.', 'Fetching the wind direction.', 'Let me get the wind direction.']}, {'tag': 'wind_gust', 'patterns': ['What is the wind gust?', 'Show wind gust', 'Current wind gust', 'Tell me the wind gust', 'wind gust today', "Today's wind gust", 'Can you check the wind gust?', 'I need the wind gust', 'Give me the wind gust', 'Latest wind gust', 'Wind gust in Delhi', 'Wind gust in Mumbai', 'Wind gust in Chennai', 'Wind gust in Hyderabad', 'Wind gust in Bengaluru', 'Wind gust in Kolkata', 'Wind gust in Visakhapatnam'], 'responses': ['Checking the wind gust.', 'Fetching the wind gust.', 'Let me get the wind gust.']}, {'tag': 'pressure', 'patterns': ['What is the air pressure?', 'Show air pressure', 'Current air pressure', 'Tell me the air pressure', 'air pressure today', "Today's air pressure", 'Can you check the air pressure?', 'I need the air pressure', 'Give me the air pressure', 'Latest air pressure', 'Air pressure in Delhi', 'Air pressure in Mumbai', 'Air pressure in Chennai', 'Air pressure in Hyderabad', 'Air pressure in Bengaluru', 'Air pressure in Kolkata', 'Air pressure in Visakhapatnam'], 'responses': ['Checking the air pressure.', 'Fetching the air pressure.', 'Let me get the air pressure.']}, {'tag': 'visibility', 'patterns': ['What is the visibility?', 'Show visibility', 'Current visibility', 'Tell me the visibility', 'visibility today', "Today's visibility", 'Can you check the visibility?', 'I need the visibility', 'Give me the visibility', 'Latest visibility', 'Visibility in Delhi', 'Visibility in Mumbai', 'Visibility in Chennai', 'Visibility in Hyderabad', 'Visibility in Bengaluru', 'Visibility in Kolkata', 'Visibility in Visakhapatnam'], 'responses': ['Checking the visibility.', 'Fetching the visibility.', 'Let me get the visibility.']}, {'tag': 'cloud_percentage', 'patterns': ['What is the cloud coverage?', 'Show cloud coverage', 'Current cloud coverage', 'Tell me the cloud coverage', 'cloud coverage today', "Today's cloud coverage", 'Can you check the cloud coverage?', 'I need the cloud coverage', 'Give me the cloud coverage', 'Latest cloud coverage', 'Cloud coverage in Delhi', 'Cloud coverage in Mumbai', 'Cloud coverage in Chennai', 'Cloud coverage in Hyderabad', 'Cloud coverage in Bengaluru', 'Cloud coverage in Kolkata', 'Cloud coverage in Visakhapatnam'], 'responses': ['Checking the cloud coverage.', 'Fetching the cloud coverage.', 'Let me get the cloud coverage.']}, {'tag': 'weather_description', 'patterns': ['What is the weather condition?', 'Show weather condition', 'Current weather condition', 'Tell me the weather condition', 'weather condition today', "Today's weather condition", 'Can you check the weather condition?', 'I need the weather condition', 'Give me the weather condition', 'Latest weather condition', 'Weather condition in Delhi', 'Weather condition in Mumbai', 'Weather condition in Chennai', 'Weather condition in Hyderabad', 'Weather condition in Bengaluru', 'Weather condition in Kolkata', 'Weather condition in Visakhapatnam'], 'responses': ['Checking the weather condition.', 'Fetching the weather condition.', 'Let me get the weather condition.']}, {'tag': 'rain_status', 'patterns': ['What is the rain status?', 'Show rain status', 'Current rain status', 'Tell me the rain status', 'rain status today', "Today's rain status", 'Can you check the rain status?', 'I need the rain status', 'Give me the rain status', 'Latest rain status', 'Rain status in Delhi', 'Rain status in Mumbai', 'Rain status in Chennai', 'Rain status in Hyderabad', 'Rain status in Bengaluru', 'Rain status in Kolkata', 'Rain status in Visakhapatnam'], 'responses': ['Checking the rain status.', 'Fetching the rain status.', 'Let me get the rain status.']}, {'tag': 'snow_status', 'patterns': ['What is the snow status?', 'Show snow status', 'Current snow status', 'Tell me the snow status', 'snow status today', "Today's snow status", 'Can you check the snow status?', 'I need the snow status', 'Give me the snow status', 'Latest snow status', 'Snow status in Delhi', 'Snow status in Mumbai', 'Snow status in Chennai', 'Snow status in Hyderabad', 'Snow status in Bengaluru', 'Snow status in Kolkata', 'Snow status in Visakhapatnam'], 'responses': ['Checking the snow status.', 'Fetching the snow status.', 'Let me get the snow status.']}, {'tag': 'sunrise_time', 'patterns': ['What is the sunrise time?', 'Show sunrise time', 'Current sunrise time', 'Tell me the sunrise time', 'sunrise time today', "Today's sunrise time", 'Can you check the sunrise time?', 'I need the sunrise time', 'Give me the sunrise time', 'Latest sunrise time', 'Sunrise time in Delhi', 'Sunrise time in Mumbai', 'Sunrise time in Chennai', 'Sunrise time in Hyderabad', 'Sunrise time in Bengaluru', 'Sunrise time in Kolkata', 'Sunrise time in Visakhapatnam'], 'responses': ['Checking the sunrise time.', 'Fetching the sunrise time.', 'Let me get the sunrise time.']}, {'tag': 'sunset_time', 'patterns': ['What is the sunset time?', 'Show sunset time', 'Current sunset time', 'Tell me the sunset time', 'sunset time today', "Today's sunset time", 'Can you check the sunset time?', 'I need the sunset time', 'Give me the sunset time', 'Latest sunset time', 'Sunset time in Delhi', 'Sunset time in Mumbai', 'Sunset time in Chennai', 'Sunset time in Hyderabad', 'Sunset time in Bengaluru', 'Sunset time in Kolkata', 'Sunset time in Visakhapatnam'], 'responses': ['Checking the sunset time.', 'Fetching the sunset time.', 'Let me get the sunset time.']}, {'tag': 'local_timezone', 'patterns': ['What is the timezone?', 'Show timezone', 'Current timezone', 'Tell me the timezone', 'timezone today', "Today's timezone", 'Can you check the timezone?', 'I need the timezone', 'Give me the timezone', 'Latest timezone', 'Timezone in Delhi', 'Timezone in Mumbai', 'Timezone in Chennai', 'Timezone in Hyderabad', 'Timezone in Bengaluru', 'Timezone in Kolkata', 'Timezone in Visakhapatnam'], 'responses': ['Checking the timezone.', 'Fetching the timezone.', 'Let me get the timezone.']}, {'tag': 'unknown', 'patterns': ['asdf', 'random question', 'blah blah'], 'responses': ["Sorry, I didn't understand. Please ask a weather-related question."]}]}

In [7]:
#Step 4: Extract Patterns, Tags, and Responses
patterns = []
tags = []
responses = []

In [8]:
for intent in intents["intents"]:
    print(intent["tag"])
    print(intent["patterns"])
    print(intent["responses"])
    print("-----------------")

greeting
['hi', 'hello', 'hey', 'good morning', 'good evening', 'hey bot', 'hello chatbot', 'hi there', 'greetings', 'good afternoon']
['Hello!', 'Hi! How can I help?', 'Welcome!']
-----------------
goodbye
['bye', 'goodbye', 'see you', 'take care', 'catch you later', 'bye bot', 'see you later']
['Goodbye!', 'See you soon!', 'Take care!']
-----------------
thanks
['thanks', 'thank you', 'thanks a lot', 'much appreciated', 'thank you so much', 'awesome thanks']
["You're welcome!", 'Happy to help!', 'Anytime!']
-----------------
help
['help', 'what can you do', 'show commands', 'how can you help', 'features', 'supported weather information']
['I can provide weather information for cities.']
-----------------
bot_name
['who are you', 'what is your name', 'your name', 'are you a chatbot', 'introduce yourself']
["I'm your Weather Chatbot."]
-----------------
weather_overview
['weather today', 'current weather', 'weather report', 'weather update', 'how is the weather', "today's weather", 'show weather', 'complete weather report', 'Weather in Delhi', 'Weather in Mumbai', 'Weather in Chennai', 'Weather in Hyderabad', 'Weather in Bengaluru', 'Weather in Kolkata', 'Weather in Visakhapatnam']
['Fetching complete weather details.', 'Checking the latest weather.']
-----------------
current_temperature
['What is the current temperature?', 'Show current temperature', 'Current current temperature', 'Tell me the current temperature', 'current temperature today', "Today's current temperature", 'Can you check the current temperature?', 'I need the current temperature', 'Give me the current temperature', 'Latest current temperature', 'Current temperature in Delhi', 'Current temperature in Mumbai', 'Current temperature in Chennai', 'Current temperature in Hyderabad', 'Current temperature in Bengaluru', 'Current temperature in Kolkata', 'Current temperature in Visakhapatnam']
['Checking the current temperature.', 'Fetching the current temperature.', 'Let me get the current temperature.']
-----------------
feels_like_temperature
['What is the feels like temperature?', 'Show feels like temperature', 'Current feels like temperature', 'Tell me the feels like temperature', 'feels like temperature today', "Today's feels like temperature", 'Can you check the feels like temperature?', 'I need the feels like temperature', 'Give me the feels like temperature', 'Latest feels like temperature', 'Feels like temperature in Delhi', 'Feels like temperature in Mumbai', 'Feels like temperature in Chennai', 'Feels like temperature in Hyderabad', 'Feels like temperature in Bengaluru', 'Feels like temperature in Kolkata', 'Feels like temperature in Visakhapatnam']
['Checking the feels like temperature.', 'Fetching the feels like temperature.', 'Let me get the feels like temperature.']
-----------------
minimum_temperature
['What is the minimum temperature?', 'Show minimum temperature', 'Current minimum temperature', 'Tell me the minimum temperature', 'minimum temperature today', "Today's minimum temperature", 'Can you check the minimum temperature?', 'I need the minimum temperature', 'Give me the minimum temperature', 'Latest minimum temperature', 'Minimum temperature in Delhi', 'Minimum temperature in Mumbai', 'Minimum temperature in Chennai', 'Minimum temperature in Hyderabad', 'Minimum temperature in Bengaluru', 'Minimum temperature in Kolkata', 'Minimum temperature in Visakhapatnam']
['Checking the minimum temperature.', 'Fetching the minimum temperature.', 'Let me get the minimum temperature.']
-----------------
maximum_temperature
['What is the maximum temperature?', 'Show maximum temperature', 'Current maximum temperature', 'Tell me the maximum temperature', 'maximum temperature today', "Today's maximum temperature", 'Can you check the maximum temperature?', 'I need the maximum temperature', 'Give me the maximum temperature', 'Latest maximum temperature', 'Maximum temperature in Delhi', 'Maximum temperature in Mumbai', 'Maximum temperature in Chennai', 'Maximum temperature in Hyderabad', 'Maximum temperature in Bengaluru', 'Maximum temperature in Kolkata', 'Maximum temperature in Visakhapatnam']
['Checking the maximum temperature.', 'Fetching the maximum temperature.', 'Let me get the maximum temperature.']
-----------------
humidity
['What is the humidity?', 'Show humidity', 'Current humidity', 'Tell me the humidity', 'humidity today', "Today's humidity", 'Can you check the humidity?', 'I need the humidity', 'Give me the humidity', 'Latest humidity', 'Humidity in Delhi', 'Humidity in Mumbai', 'Humidity in Chennai', 'Humidity in Hyderabad', 'Humidity in Bengaluru', 'Humidity in Kolkata', 'Humidity in Visakhapatnam']
['Checking the humidity.', 'Fetching the humidity.', 'Let me get the humidity.']
-----------------
wind_speed
['What is the wind speed?', 'Show wind speed', 'Current wind speed', 'Tell me the wind speed', 'wind speed today', "Today's wind speed", 'Can you check the wind speed?', 'I need the wind speed', 'Give me the wind speed', 'Latest wind speed', 'Wind speed in Delhi', 'Wind speed in Mumbai', 'Wind speed in Chennai', 'Wind speed in Hyderabad', 'Wind speed in Bengaluru', 'Wind speed in Kolkata', 'Wind speed in Visakhapatnam']
['Checking the wind speed.', 'Fetching the wind speed.', 'Let me get the wind speed.']
-----------------
wind_direction
['What is the wind direction?', 'Show wind direction', 'Current wind direction', 'Tell me the wind direction', 'wind direction today', "Today's wind direction", 'Can you check the wind direction?', 'I need the wind direction', 'Give me the wind direction', 'Latest wind direction', 'Wind direction in Delhi', 'Wind direction in Mumbai', 'Wind direction in Chennai', 'Wind direction in Hyderabad', 'Wind direction in Bengaluru', 'Wind direction in Kolkata', 'Wind direction in Visakhapatnam']
['Checking the wind direction.', 'Fetching the wind direction.', 'Let me get the wind direction.']
-----------------
wind_gust
['What is the wind gust?', 'Show wind gust', 'Current wind gust', 'Tell me the wind gust', 'wind gust today', "Today's wind gust", 'Can you check the wind gust?', 'I need the wind gust', 'Give me the wind gust', 'Latest wind gust', 'Wind gust in Delhi', 'Wind gust in Mumbai', 'Wind gust in Chennai', 'Wind gust in Hyderabad', 'Wind gust in Bengaluru', 'Wind gust in Kolkata', 'Wind gust in Visakhapatnam']
['Checking the wind gust.', 'Fetching the wind gust.', 'Let me get the wind gust.']
-----------------
pressure
['What is the air pressure?', 'Show air pressure', 'Current air pressure', 'Tell me the air pressure', 'air pressure today', "Today's air pressure", 'Can you check the air pressure?', 'I need the air pressure', 'Give me the air pressure', 'Latest air pressure', 'Air pressure in Delhi', 'Air pressure in Mumbai', 'Air pressure in Chennai', 'Air pressure in Hyderabad', 'Air pressure in Bengaluru', 'Air pressure in Kolkata', 'Air pressure in Visakhapatnam']
['Checking the air pressure.', 'Fetching the air pressure.', 'Let me get the air pressure.']
-----------------
visibility
['What is the visibility?', 'Show visibility', 'Current visibility', 'Tell me the visibility', 'visibility today', "Today's visibility", 'Can you check the visibility?', 'I need the visibility', 'Give me the visibility', 'Latest visibility', 'Visibility in Delhi', 'Visibility in Mumbai', 'Visibility in Chennai', 'Visibility in Hyderabad', 'Visibility in Bengaluru', 'Visibility in Kolkata', 'Visibility in Visakhapatnam']
['Checking the visibility.', 'Fetching the visibility.', 'Let me get the visibility.']
-----------------
cloud_percentage
['What is the cloud coverage?', 'Show cloud coverage', 'Current cloud coverage', 'Tell me the cloud coverage', 'cloud coverage today', "Today's cloud coverage", 'Can you check the cloud coverage?', 'I need the cloud coverage', 'Give me the cloud coverage', 'Latest cloud coverage', 'Cloud coverage in Delhi', 'Cloud coverage in Mumbai', 'Cloud coverage in Chennai', 'Cloud coverage in Hyderabad', 'Cloud coverage in Bengaluru', 'Cloud coverage in Kolkata', 'Cloud coverage in Visakhapatnam']
['Checking the cloud coverage.', 'Fetching the cloud coverage.', 'Let me get the cloud coverage.']
-----------------
weather_description
['What is the weather condition?', 'Show weather condition', 'Current weather condition', 'Tell me the weather condition', 'weather condition today', "Today's weather condition", 'Can you check the weather condition?', 'I need the weather condition', 'Give me the weather condition', 'Latest weather condition', 'Weather condition in Delhi', 'Weather condition in Mumbai', 'Weather condition in Chennai', 'Weather condition in Hyderabad', 'Weather condition in Bengaluru', 'Weather condition in Kolkata', 'Weather condition in Visakhapatnam']
['Checking the weather condition.', 'Fetching the weather condition.', 'Let me get the weather condition.']
-----------------
rain_status
['What is the rain status?', 'Show rain status', 'Current rain status', 'Tell me the rain status', 'rain status today', "Today's rain status", 'Can you check the rain status?', 'I need the rain status', 'Give me the rain status', 'Latest rain status', 'Rain status in Delhi', 'Rain status in Mumbai', 'Rain status in Chennai', 'Rain status in Hyderabad', 'Rain status in Bengaluru', 'Rain status in Kolkata', 'Rain status in Visakhapatnam']
['Checking the rain status.', 'Fetching the rain status.', 'Let me get the rain status.']
-----------------
snow_status
['What is the snow status?', 'Show snow status', 'Current snow status', 'Tell me the snow status', 'snow status today', "Today's snow status", 'Can you check the snow status?', 'I need the snow status', 'Give me the snow status', 'Latest snow status', 'Snow status in Delhi', 'Snow status in Mumbai', 'Snow status in Chennai', 'Snow status in Hyderabad', 'Snow status in Bengaluru', 'Snow status in Kolkata', 'Snow status in Visakhapatnam']
['Checking the snow status.', 'Fetching the snow status.', 'Let me get the snow status.']
-----------------
sunrise_time
['What is the sunrise time?', 'Show sunrise time', 'Current sunrise time', 'Tell me the sunrise time', 'sunrise time today', "Today's sunrise time", 'Can you check the sunrise time?', 'I need the sunrise time', 'Give me the sunrise time', 'Latest sunrise time', 'Sunrise time in Delhi', 'Sunrise time in Mumbai', 'Sunrise time in Chennai', 'Sunrise time in Hyderabad', 'Sunrise time in Bengaluru', 'Sunrise time in Kolkata', 'Sunrise time in Visakhapatnam']
['Checking the sunrise time.', 'Fetching the sunrise time.', 'Let me get the sunrise time.']
-----------------
sunset_time
['What is the sunset time?', 'Show sunset time', 'Current sunset time', 'Tell me the sunset time', 'sunset time today', "Today's sunset time", 'Can you check the sunset time?', 'I need the sunset time', 'Give me the sunset time', 'Latest sunset time', 'Sunset time in Delhi', 'Sunset time in Mumbai', 'Sunset time in Chennai', 'Sunset time in Hyderabad', 'Sunset time in Bengaluru', 'Sunset time in Kolkata', 'Sunset time in Visakhapatnam']
['Checking the sunset time.', 'Fetching the sunset time.', 'Let me get the sunset time.']
-----------------
local_timezone
['What is the timezone?', 'Show timezone', 'Current timezone', 'Tell me the timezone', 'timezone today', "Today's timezone", 'Can you check the timezone?', 'I need the timezone', 'Give me the timezone', 'Latest timezone', 'Timezone in Delhi', 'Timezone in Mumbai', 'Timezone in Chennai', 'Timezone in Hyderabad', 'Timezone in Bengaluru', 'Timezone in Kolkata', 'Timezone in Visakhapatnam']
['Checking the timezone.', 'Fetching the timezone.', 'Let me get the timezone.']
-----------------
unknown
['asdf', 'random question', 'blah blah']
["Sorry, I didn't understand. Please ask a weather-related question."]
-----------------

In [9]:
#for understanding
for intent in intents["intents"]:
    tag=intent["tag"]
    patterns=intent["patterns"]
    responses=intent["responses"]
    print(tag)
    print("------------------")
    print(patterns)
    print("------------------")
    print(responses)
    print("------------------")
print("-************************************************-----------------")
#only last vale gets printed bcoz we looped but not appended every looped element so automatically for peints the last llop element and stored it
print(tag)
print("------------------")
print(patterns)
print("------------------")
print(responses)
print("------------------")
    #print("------------------")

greeting
------------------
['hi', 'hello', 'hey', 'good morning', 'good evening', 'hey bot', 'hello chatbot', 'hi there', 'greetings', 'good afternoon']
------------------
['Hello!', 'Hi! How can I help?', 'Welcome!']
------------------
goodbye
------------------
['bye', 'goodbye', 'see you', 'take care', 'catch you later', 'bye bot', 'see you later']
------------------
['Goodbye!', 'See you soon!', 'Take care!']
------------------
thanks
------------------
['thanks', 'thank you', 'thanks a lot', 'much appreciated', 'thank you so much', 'awesome thanks']
------------------
["You're welcome!", 'Happy to help!', 'Anytime!']
------------------
help
------------------
['help', 'what can you do', 'show commands', 'how can you help', 'features', 'supported weather information']
------------------
['I can provide weather information for cities.']
------------------
bot_name
------------------
['who are you', 'what is your name', 'your name', 'are you a chatbot', 'introduce yourself']
------------------
["I'm your Weather Chatbot."]
------------------
weather_overview
------------------
['weather today', 'current weather', 'weather report', 'weather update', 'how is the weather', "today's weather", 'show weather', 'complete weather report', 'Weather in Delhi', 'Weather in Mumbai', 'Weather in Chennai', 'Weather in Hyderabad', 'Weather in Bengaluru', 'Weather in Kolkata', 'Weather in Visakhapatnam']
------------------
['Fetching complete weather details.', 'Checking the latest weather.']
------------------
current_temperature
------------------
['What is the current temperature?', 'Show current temperature', 'Current current temperature', 'Tell me the current temperature', 'current temperature today', "Today's current temperature", 'Can you check the current temperature?', 'I need the current temperature', 'Give me the current temperature', 'Latest current temperature', 'Current temperature in Delhi', 'Current temperature in Mumbai', 'Current temperature in Chennai', 'Current temperature in Hyderabad', 'Current temperature in Bengaluru', 'Current temperature in Kolkata', 'Current temperature in Visakhapatnam']
------------------
['Checking the current temperature.', 'Fetching the current temperature.', 'Let me get the current temperature.']
------------------
feels_like_temperature
------------------
['What is the feels like temperature?', 'Show feels like temperature', 'Current feels like temperature', 'Tell me the feels like temperature', 'feels like temperature today', "Today's feels like temperature", 'Can you check the feels like temperature?', 'I need the feels like temperature', 'Give me the feels like temperature', 'Latest feels like temperature', 'Feels like temperature in Delhi', 'Feels like temperature in Mumbai', 'Feels like temperature in Chennai', 'Feels like temperature in Hyderabad', 'Feels like temperature in Bengaluru', 'Feels like temperature in Kolkata', 'Feels like temperature in Visakhapatnam']
------------------
['Checking the feels like temperature.', 'Fetching the feels like temperature.', 'Let me get the feels like temperature.']
------------------
minimum_temperature
------------------
['What is the minimum temperature?', 'Show minimum temperature', 'Current minimum temperature', 'Tell me the minimum temperature', 'minimum temperature today', "Today's minimum temperature", 'Can you check the minimum temperature?', 'I need the minimum temperature', 'Give me the minimum temperature', 'Latest minimum temperature', 'Minimum temperature in Delhi', 'Minimum temperature in Mumbai', 'Minimum temperature in Chennai', 'Minimum temperature in Hyderabad', 'Minimum temperature in Bengaluru', 'Minimum temperature in Kolkata', 'Minimum temperature in Visakhapatnam']
------------------
['Checking the minimum temperature.', 'Fetching the minimum temperature.', 'Let me get the minimum temperature.']
------------------
maximum_temperature
------------------
['What is the maximum temperature?', 'Show maximum temperature', 'Current maximum temperature', 'Tell me the maximum temperature', 'maximum temperature today', "Today's maximum temperature", 'Can you check the maximum temperature?', 'I need the maximum temperature', 'Give me the maximum temperature', 'Latest maximum temperature', 'Maximum temperature in Delhi', 'Maximum temperature in Mumbai', 'Maximum temperature in Chennai', 'Maximum temperature in Hyderabad', 'Maximum temperature in Bengaluru', 'Maximum temperature in Kolkata', 'Maximum temperature in Visakhapatnam']
------------------
['Checking the maximum temperature.', 'Fetching the maximum temperature.', 'Let me get the maximum temperature.']
------------------
humidity
------------------
['What is the humidity?', 'Show humidity', 'Current humidity', 'Tell me the humidity', 'humidity today', "Today's humidity", 'Can you check the humidity?', 'I need the humidity', 'Give me the humidity', 'Latest humidity', 'Humidity in Delhi', 'Humidity in Mumbai', 'Humidity in Chennai', 'Humidity in Hyderabad', 'Humidity in Bengaluru', 'Humidity in Kolkata', 'Humidity in Visakhapatnam']
------------------
['Checking the humidity.', 'Fetching the humidity.', 'Let me get the humidity.']
------------------
wind_speed
------------------
['What is the wind speed?', 'Show wind speed', 'Current wind speed', 'Tell me the wind speed', 'wind speed today', "Today's wind speed", 'Can you check the wind speed?', 'I need the wind speed', 'Give me the wind speed', 'Latest wind speed', 'Wind speed in Delhi', 'Wind speed in Mumbai', 'Wind speed in Chennai', 'Wind speed in Hyderabad', 'Wind speed in Bengaluru', 'Wind speed in Kolkata', 'Wind speed in Visakhapatnam']
------------------
['Checking the wind speed.', 'Fetching the wind speed.', 'Let me get the wind speed.']
------------------
wind_direction
------------------
['What is the wind direction?', 'Show wind direction', 'Current wind direction', 'Tell me the wind direction', 'wind direction today', "Today's wind direction", 'Can you check the wind direction?', 'I need the wind direction', 'Give me the wind direction', 'Latest wind direction', 'Wind direction in Delhi', 'Wind direction in Mumbai', 'Wind direction in Chennai', 'Wind direction in Hyderabad', 'Wind direction in Bengaluru', 'Wind direction in Kolkata', 'Wind direction in Visakhapatnam']
------------------
['Checking the wind direction.', 'Fetching the wind direction.', 'Let me get the wind direction.']
------------------
wind_gust
------------------
['What is the wind gust?', 'Show wind gust', 'Current wind gust', 'Tell me the wind gust', 'wind gust today', "Today's wind gust", 'Can you check the wind gust?', 'I need the wind gust', 'Give me the wind gust', 'Latest wind gust', 'Wind gust in Delhi', 'Wind gust in Mumbai', 'Wind gust in Chennai', 'Wind gust in Hyderabad', 'Wind gust in Bengaluru', 'Wind gust in Kolkata', 'Wind gust in Visakhapatnam']
------------------
['Checking the wind gust.', 'Fetching the wind gust.', 'Let me get the wind gust.']
------------------
pressure
------------------
['What is the air pressure?', 'Show air pressure', 'Current air pressure', 'Tell me the air pressure', 'air pressure today', "Today's air pressure", 'Can you check the air pressure?', 'I need the air pressure', 'Give me the air pressure', 'Latest air pressure', 'Air pressure in Delhi', 'Air pressure in Mumbai', 'Air pressure in Chennai', 'Air pressure in Hyderabad', 'Air pressure in Bengaluru', 'Air pressure in Kolkata', 'Air pressure in Visakhapatnam']
------------------
['Checking the air pressure.', 'Fetching the air pressure.', 'Let me get the air pressure.']
------------------
visibility
------------------
['What is the visibility?', 'Show visibility', 'Current visibility', 'Tell me the visibility', 'visibility today', "Today's visibility", 'Can you check the visibility?', 'I need the visibility', 'Give me the visibility', 'Latest visibility', 'Visibility in Delhi', 'Visibility in Mumbai', 'Visibility in Chennai', 'Visibility in Hyderabad', 'Visibility in Bengaluru', 'Visibility in Kolkata', 'Visibility in Visakhapatnam']
------------------
['Checking the visibility.', 'Fetching the visibility.', 'Let me get the visibility.']
------------------
cloud_percentage
------------------
['What is the cloud coverage?', 'Show cloud coverage', 'Current cloud coverage', 'Tell me the cloud coverage', 'cloud coverage today', "Today's cloud coverage", 'Can you check the cloud coverage?', 'I need the cloud coverage', 'Give me the cloud coverage', 'Latest cloud coverage', 'Cloud coverage in Delhi', 'Cloud coverage in Mumbai', 'Cloud coverage in Chennai', 'Cloud coverage in Hyderabad', 'Cloud coverage in Bengaluru', 'Cloud coverage in Kolkata', 'Cloud coverage in Visakhapatnam']
------------------
['Checking the cloud coverage.', 'Fetching the cloud coverage.', 'Let me get the cloud coverage.']
------------------
weather_description
------------------
['What is the weather condition?', 'Show weather condition', 'Current weather condition', 'Tell me the weather condition', 'weather condition today', "Today's weather condition", 'Can you check the weather condition?', 'I need the weather condition', 'Give me the weather condition', 'Latest weather condition', 'Weather condition in Delhi', 'Weather condition in Mumbai', 'Weather condition in Chennai', 'Weather condition in Hyderabad', 'Weather condition in Bengaluru', 'Weather condition in Kolkata', 'Weather condition in Visakhapatnam']
------------------
['Checking the weather condition.', 'Fetching the weather condition.', 'Let me get the weather condition.']
------------------
rain_status
------------------
['What is the rain status?', 'Show rain status', 'Current rain status', 'Tell me the rain status', 'rain status today', "Today's rain status", 'Can you check the rain status?', 'I need the rain status', 'Give me the rain status', 'Latest rain status', 'Rain status in Delhi', 'Rain status in Mumbai', 'Rain status in Chennai', 'Rain status in Hyderabad', 'Rain status in Bengaluru', 'Rain status in Kolkata', 'Rain status in Visakhapatnam']
------------------
['Checking the rain status.', 'Fetching the rain status.', 'Let me get the rain status.']
------------------
snow_status
------------------
['What is the snow status?', 'Show snow status', 'Current snow status', 'Tell me the snow status', 'snow status today', "Today's snow status", 'Can you check the snow status?', 'I need the snow status', 'Give me the snow status', 'Latest snow status', 'Snow status in Delhi', 'Snow status in Mumbai', 'Snow status in Chennai', 'Snow status in Hyderabad', 'Snow status in Bengaluru', 'Snow status in Kolkata', 'Snow status in Visakhapatnam']
------------------
['Checking the snow status.', 'Fetching the snow status.', 'Let me get the snow status.']
------------------
sunrise_time
------------------
['What is the sunrise time?', 'Show sunrise time', 'Current sunrise time', 'Tell me the sunrise time', 'sunrise time today', "Today's sunrise time", 'Can you check the sunrise time?', 'I need the sunrise time', 'Give me the sunrise time', 'Latest sunrise time', 'Sunrise time in Delhi', 'Sunrise time in Mumbai', 'Sunrise time in Chennai', 'Sunrise time in Hyderabad', 'Sunrise time in Bengaluru', 'Sunrise time in Kolkata', 'Sunrise time in Visakhapatnam']
------------------
['Checking the sunrise time.', 'Fetching the sunrise time.', 'Let me get the sunrise time.']
------------------
sunset_time
------------------
['What is the sunset time?', 'Show sunset time', 'Current sunset time', 'Tell me the sunset time', 'sunset time today', "Today's sunset time", 'Can you check the sunset time?', 'I need the sunset time', 'Give me the sunset time', 'Latest sunset time', 'Sunset time in Delhi', 'Sunset time in Mumbai', 'Sunset time in Chennai', 'Sunset time in Hyderabad', 'Sunset time in Bengaluru', 'Sunset time in Kolkata', 'Sunset time in Visakhapatnam']
------------------
['Checking the sunset time.', 'Fetching the sunset time.', 'Let me get the sunset time.']
------------------
local_timezone
------------------
['What is the timezone?', 'Show timezone', 'Current timezone', 'Tell me the timezone', 'timezone today', "Today's timezone", 'Can you check the timezone?', 'I need the timezone', 'Give me the timezone', 'Latest timezone', 'Timezone in Delhi', 'Timezone in Mumbai', 'Timezone in Chennai', 'Timezone in Hyderabad', 'Timezone in Bengaluru', 'Timezone in Kolkata', 'Timezone in Visakhapatnam']
------------------
['Checking the timezone.', 'Fetching the timezone.', 'Let me get the timezone.']
------------------
unknown
------------------
['asdf', 'random question', 'blah blah']
------------------
["Sorry, I didn't understand. Please ask a weather-related question."]
------------------
-************************************************-----------------
unknown
------------------
['asdf', 'random question', 'blah blah']
------------------
["Sorry, I didn't understand. Please ask a weather-related question."]
------------------

In [10]:
# Empty lists

patterns = []
tags = []
responses = []

# Loop through every intent

for intent in intents["intents"]:

    # Get the intent tag
    tag = intent["tag"]

    # Store all responses of this intent
    responses.append(intent["responses"])

    # Loop through every pattern of this intent
    for pattern in intent["patterns"]:

        # Store the pattern
        patterns.append(pattern)

        # Store its corresponding tag
        tags.append(tag)

In [11]:
print(len(tags))
print(len(patterns))
print(len(responses))

print(tags)
print("------------------")
print(patterns)
print("------------------")
print(responses)

341
341
24
['greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'greeting', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'goodbye', 'thanks', 'thanks', 'thanks', 'thanks', 'thanks', 'thanks', 'help', 'help', 'help', 'help', 'help', 'help', 'bot_name', 'bot_name', 'bot_name', 'bot_name', 'bot_name', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'weather_overview', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'current_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'feels_like_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'minimum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'maximum_temperature', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'humidity', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_speed', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_direction', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'wind_gust', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'pressure', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'visibility', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'cloud_percentage', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'weather_description', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'rain_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'snow_status', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunrise_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'sunset_time', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'local_timezone', 'unknown', 'unknown', 'unknown']
------------------
['hi', 'hello', 'hey', 'good morning', 'good evening', 'hey bot', 'hello chatbot', 'hi there', 'greetings', 'good afternoon', 'bye', 'goodbye', 'see you', 'take care', 'catch you later', 'bye bot', 'see you later', 'thanks', 'thank you', 'thanks a lot', 'much appreciated', 'thank you so much', 'awesome thanks', 'help', 'what can you do', 'show commands', 'how can you help', 'features', 'supported weather information', 'who are you', 'what is your name', 'your name', 'are you a chatbot', 'introduce yourself', 'weather today', 'current weather', 'weather report', 'weather update', 'how is the weather', "today's weather", 'show weather', 'complete weather report', 'Weather in Delhi', 'Weather in Mumbai', 'Weather in Chennai', 'Weather in Hyderabad', 'Weather in Bengaluru', 'Weather in Kolkata', 'Weather in Visakhapatnam', 'What is the current temperature?', 'Show current temperature', 'Current current temperature', 'Tell me the current temperature', 'current temperature today', "Today's current temperature", 'Can you check the current temperature?', 'I need the current temperature', 'Give me the current temperature', 'Latest current temperature', 'Current temperature in Delhi', 'Current temperature in Mumbai', 'Current temperature in Chennai', 'Current temperature in Hyderabad', 'Current temperature in Bengaluru', 'Current temperature in Kolkata', 'Current temperature in Visakhapatnam', 'What is the feels like temperature?', 'Show feels like temperature', 'Current feels like temperature', 'Tell me the feels like temperature', 'feels like temperature today', "Today's feels like temperature", 'Can you check the feels like temperature?', 'I need the feels like temperature', 'Give me the feels like temperature', 'Latest feels like temperature', 'Feels like temperature in Delhi', 'Feels like temperature in Mumbai', 'Feels like temperature in Chennai', 'Feels like temperature in Hyderabad', 'Feels like temperature in Bengaluru', 'Feels like temperature in Kolkata', 'Feels like temperature in Visakhapatnam', 'What is the minimum temperature?', 'Show minimum temperature', 'Current minimum temperature', 'Tell me the minimum temperature', 'minimum temperature today', "Today's minimum temperature", 'Can you check the minimum temperature?', 'I need the minimum temperature', 'Give me the minimum temperature', 'Latest minimum temperature', 'Minimum temperature in Delhi', 'Minimum temperature in Mumbai', 'Minimum temperature in Chennai', 'Minimum temperature in Hyderabad', 'Minimum temperature in Bengaluru', 'Minimum temperature in Kolkata', 'Minimum temperature in Visakhapatnam', 'What is the maximum temperature?', 'Show maximum temperature', 'Current maximum temperature', 'Tell me the maximum temperature', 'maximum temperature today', "Today's maximum temperature", 'Can you check the maximum temperature?', 'I need the maximum temperature', 'Give me the maximum temperature', 'Latest maximum temperature', 'Maximum temperature in Delhi', 'Maximum temperature in Mumbai', 'Maximum temperature in Chennai', 'Maximum temperature in Hyderabad', 'Maximum temperature in Bengaluru', 'Maximum temperature in Kolkata', 'Maximum temperature in Visakhapatnam', 'What is the humidity?', 'Show humidity', 'Current humidity', 'Tell me the humidity', 'humidity today', "Today's humidity", 'Can you check the humidity?', 'I need the humidity', 'Give me the humidity', 'Latest humidity', 'Humidity in Delhi', 'Humidity in Mumbai', 'Humidity in Chennai', 'Humidity in Hyderabad', 'Humidity in Bengaluru', 'Humidity in Kolkata', 'Humidity in Visakhapatnam', 'What is the wind speed?', 'Show wind speed', 'Current wind speed', 'Tell me the wind speed', 'wind speed today', "Today's wind speed", 'Can you check the wind speed?', 'I need the wind speed', 'Give me the wind speed', 'Latest wind speed', 'Wind speed in Delhi', 'Wind speed in Mumbai', 'Wind speed in Chennai', 'Wind speed in Hyderabad', 'Wind speed in Bengaluru', 'Wind speed in Kolkata', 'Wind speed in Visakhapatnam', 'What is the wind direction?', 'Show wind direction', 'Current wind direction', 'Tell me the wind direction', 'wind direction today', "Today's wind direction", 'Can you check the wind direction?', 'I need the wind direction', 'Give me the wind direction', 'Latest wind direction', 'Wind direction in Delhi', 'Wind direction in Mumbai', 'Wind direction in Chennai', 'Wind direction in Hyderabad', 'Wind direction in Bengaluru', 'Wind direction in Kolkata', 'Wind direction in Visakhapatnam', 'What is the wind gust?', 'Show wind gust', 'Current wind gust', 'Tell me the wind gust', 'wind gust today', "Today's wind gust", 'Can you check the wind gust?', 'I need the wind gust', 'Give me the wind gust', 'Latest wind gust', 'Wind gust in Delhi', 'Wind gust in Mumbai', 'Wind gust in Chennai', 'Wind gust in Hyderabad', 'Wind gust in Bengaluru', 'Wind gust in Kolkata', 'Wind gust in Visakhapatnam', 'What is the air pressure?', 'Show air pressure', 'Current air pressure', 'Tell me the air pressure', 'air pressure today', "Today's air pressure", 'Can you check the air pressure?', 'I need the air pressure', 'Give me the air pressure', 'Latest air pressure', 'Air pressure in Delhi', 'Air pressure in Mumbai', 'Air pressure in Chennai', 'Air pressure in Hyderabad', 'Air pressure in Bengaluru', 'Air pressure in Kolkata', 'Air pressure in Visakhapatnam', 'What is the visibility?', 'Show visibility', 'Current visibility', 'Tell me the visibility', 'visibility today', "Today's visibility", 'Can you check the visibility?', 'I need the visibility', 'Give me the visibility', 'Latest visibility', 'Visibility in Delhi', 'Visibility in Mumbai', 'Visibility in Chennai', 'Visibility in Hyderabad', 'Visibility in Bengaluru', 'Visibility in Kolkata', 'Visibility in Visakhapatnam', 'What is the cloud coverage?', 'Show cloud coverage', 'Current cloud coverage', 'Tell me the cloud coverage', 'cloud coverage today', "Today's cloud coverage", 'Can you check the cloud coverage?', 'I need the cloud coverage', 'Give me the cloud coverage', 'Latest cloud coverage', 'Cloud coverage in Delhi', 'Cloud coverage in Mumbai', 'Cloud coverage in Chennai', 'Cloud coverage in Hyderabad', 'Cloud coverage in Bengaluru', 'Cloud coverage in Kolkata', 'Cloud coverage in Visakhapatnam', 'What is the weather condition?', 'Show weather condition', 'Current weather condition', 'Tell me the weather condition', 'weather condition today', "Today's weather condition", 'Can you check the weather condition?', 'I need the weather condition', 'Give me the weather condition', 'Latest weather condition', 'Weather condition in Delhi', 'Weather condition in Mumbai', 'Weather condition in Chennai', 'Weather condition in Hyderabad', 'Weather condition in Bengaluru', 'Weather condition in Kolkata', 'Weather condition in Visakhapatnam', 'What is the rain status?', 'Show rain status', 'Current rain status', 'Tell me the rain status', 'rain status today', "Today's rain status", 'Can you check the rain status?', 'I need the rain status', 'Give me the rain status', 'Latest rain status', 'Rain status in Delhi', 'Rain status in Mumbai', 'Rain status in Chennai', 'Rain status in Hyderabad', 'Rain status in Bengaluru', 'Rain status in Kolkata', 'Rain status in Visakhapatnam', 'What is the snow status?', 'Show snow status', 'Current snow status', 'Tell me the snow status', 'snow status today', "Today's snow status", 'Can you check the snow status?', 'I need the snow status', 'Give me the snow status', 'Latest snow status', 'Snow status in Delhi', 'Snow status in Mumbai', 'Snow status in Chennai', 'Snow status in Hyderabad', 'Snow status in Bengaluru', 'Snow status in Kolkata', 'Snow status in Visakhapatnam', 'What is the sunrise time?', 'Show sunrise time', 'Current sunrise time', 'Tell me the sunrise time', 'sunrise time today', "Today's sunrise time", 'Can you check the sunrise time?', 'I need the sunrise time', 'Give me the sunrise time', 'Latest sunrise time', 'Sunrise time in Delhi', 'Sunrise time in Mumbai', 'Sunrise time in Chennai', 'Sunrise time in Hyderabad', 'Sunrise time in Bengaluru', 'Sunrise time in Kolkata', 'Sunrise time in Visakhapatnam', 'What is the sunset time?', 'Show sunset time', 'Current sunset time', 'Tell me the sunset time', 'sunset time today', "Today's sunset time", 'Can you check the sunset time?', 'I need the sunset time', 'Give me the sunset time', 'Latest sunset time', 'Sunset time in Delhi', 'Sunset time in Mumbai', 'Sunset time in Chennai', 'Sunset time in Hyderabad', 'Sunset time in Bengaluru', 'Sunset time in Kolkata', 'Sunset time in Visakhapatnam', 'What is the timezone?', 'Show timezone', 'Current timezone', 'Tell me the timezone', 'timezone today', "Today's timezone", 'Can you check the timezone?', 'I need the timezone', 'Give me the timezone', 'Latest timezone', 'Timezone in Delhi', 'Timezone in Mumbai', 'Timezone in Chennai', 'Timezone in Hyderabad', 'Timezone in Bengaluru', 'Timezone in Kolkata', 'Timezone in Visakhapatnam', 'asdf', 'random question', 'blah blah']
------------------
[['Hello!', 'Hi! How can I help?', 'Welcome!'], ['Goodbye!', 'See you soon!', 'Take care!'], ["You're welcome!", 'Happy to help!', 'Anytime!'], ['I can provide weather information for cities.'], ["I'm your Weather Chatbot."], ['Fetching complete weather details.', 'Checking the latest weather.'], ['Checking the current temperature.', 'Fetching the current temperature.', 'Let me get the current temperature.'], ['Checking the feels like temperature.', 'Fetching the feels like temperature.', 'Let me get the feels like temperature.'], ['Checking the minimum temperature.', 'Fetching the minimum temperature.', 'Let me get the minimum temperature.'], ['Checking the maximum temperature.', 'Fetching the maximum temperature.', 'Let me get the maximum temperature.'], ['Checking the humidity.', 'Fetching the humidity.', 'Let me get the humidity.'], ['Checking the wind speed.', 'Fetching the wind speed.', 'Let me get the wind speed.'], ['Checking the wind direction.', 'Fetching the wind direction.', 'Let me get the wind direction.'], ['Checking the wind gust.', 'Fetching the wind gust.', 'Let me get the wind gust.'], ['Checking the air pressure.', 'Fetching the air pressure.', 'Let me get the air pressure.'], ['Checking the visibility.', 'Fetching the visibility.', 'Let me get the visibility.'], ['Checking the cloud coverage.', 'Fetching the cloud coverage.', 'Let me get the cloud coverage.'], ['Checking the weather condition.', 'Fetching the weather condition.', 'Let me get the weather condition.'], ['Checking the rain status.', 'Fetching the rain status.', 'Let me get the rain status.'], ['Checking the snow status.', 'Fetching the snow status.', 'Let me get the snow status.'], ['Checking the sunrise time.', 'Fetching the sunrise time.', 'Let me get the sunrise time.'], ['Checking the sunset time.', 'Fetching the sunset time.', 'Let me get the sunset time.'], ['Checking the timezone.', 'Fetching the timezone.', 'Let me get the timezone.'], ["Sorry, I didn't understand. Please ask a weather-related question."]]

In [12]:
#Step 5: Create a DataFrame Why do we need a DataFrame? Right now your data looks like this: patterns
#patterns['hi',...] tags['greeting', ..] so These are just two separate Python lists. Machine learning libraries can work with them, but before training, it's much easier to inspect and clean the data if it's in a table.That's exactly what a DataFrame is.

df = pd.DataFrame({
    "pattern": patterns,
    "tag": tags
})

In [13]:
print(df.head(10))
print(df.shape)
df.columns

          pattern       tag
0              hi  greeting
1           hello  greeting
2             hey  greeting
3    good morning  greeting
4    good evening  greeting
5         hey bot  greeting
6   hello chatbot  greeting
7        hi there  greeting
8       greetings  greeting
9  good afternoon  greeting
(341, 2)

Index(['pattern', 'tag'], dtype='object')

In [14]:
df.duplicated().sum
df.duplicated().sum()
df.duplicated().sum()

np.int64(0)

In [15]:
df["tag"].value_counts()

tag
wind_direction            17
rain_status               17
cloud_percentage          17
visibility                17
pressure                  17
wind_gust                 17
snow_status               17
wind_speed                17
humidity                  17
maximum_temperature       17
minimum_temperature       17
feels_like_temperature    17
current_temperature       17
sunrise_time              17
sunset_time               17
local_timezone            17
weather_description       17
weather_overview          15
greeting                  10
goodbye                    7
help                       6
thanks                     6
bot_name                   5
unknown                    3
Name: count, dtype: int64

In [16]:
df.sample(10)

                            pattern                     tag
325                  timezone today          local_timezone
209           I need the visibility              visibility
211               Latest visibility              visibility
158       I need the wind direction          wind_direction
121                  humidity today                humidity
40                     show weather        weather_overview
71   Today's feels like temperature  feels_like_temperature
299         Sunrise time in Chennai            sunrise_time
141           I need the wind speed              wind_speed
247     Weather condition in Mumbai     weather_description

In [17]:
#Step 6: Text Cleaning and Preprocessing
"""What is the Temperature?
what is the temperature
WHAT IS THE TEMPERATURE!!
What's the temperature? To a computer, these look like different sentences. So we normalize them into a consistent format.
 org text ---lowercase ----remove punctuation -----tokenization ------join words again------clean sentence 
 re.sub(pattern, replacement, string) text = "Hello!!!"   result = re.sub("!", "", text) so o/p Hello
 By default, WordNetLemmatizer assumes every word is a noun (pos='n') """
import re
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

# Create lemmatizer object
lemmatizer = WordNetLemmatizer()


def clean_text(text):

    # Convert to lowercase
    text = text.lower()

    # Remove punctuation and special characters
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)

    # Tokenize
    words = word_tokenize(text)

    # Lemmatize every word
    lemmatized_words = []

    for word in words:
        lemmatized_words.append(lemmatizer.lemmatize(word))

    words = lemmatized_words

    # Join words back into a sentence
    text = " ".join(words)

    return text
#a="What's writing?"
#print(clean_text(a))

In [18]:
"""Apply Cleaning on every sentence(pattern) in the DataFram """
df["pattern"] = df["pattern"].apply(clean_text)

In [19]:
df.head(10)

          pattern       tag
0              hi  greeting
1           hello  greeting
2             hey  greeting
3    good morning  greeting
4    good evening  greeting
5         hey bot  greeting
6   hello chatbot  greeting
7        hi there  greeting
8        greeting  greeting
9  good afternoon  greeting

In [20]:
#save it as csv file
df.to_csv("../data/cleaned_patterns.csv", index=False)

In [21]:
""" End of Step 6

At this point, your data is clean, normalized, and ready for numerical conversion.

The next step (Step 7) is to:
Convert the cleaned text into integer sequences using Keras Tokenizer.
Build the vocabulary (word_index).
Understand how words are mapped to numbers.
Prepare the sequences that will later be padded and fed into the LSTM.

This is the step where the model starts seeing numbers instead of text.
Sentence
↓
Current temperature today
↓
Split into words
↓
Current
Temperature
Today
↓
Assign IDs
↓
3
4
5
↓
Sequence
↓

[3,4,5]

step 7.1 Create Tokenizer , is an empty object. It knows nothing about your vocabulary.
Step 7.2 Learn Vocabulary
Now train the tokenizer on your dataset. What does fit_on_texts() do?
It scans every sentence.
Suppose your dataset is "hi nice"
tokenizer reades hi -> 1 nice
example
{
'hi':1,
'hello':2,
'current':3,
'temperature':4,
'humidity':5
} This dictionary is called the Word Index.


the tokenizer learns your entire vocabulary.
{
    'current': 1,
    'temperature': 2,
    'humidity': 3,
    'wind': 4,
    'speed': 5,
    'hi': 6,
    'hello': 7 ......
}This dictionary is stored inside the tokenizer.
  
  *****  word_index
         Maps each word to an integer.
         {
'temperature':1,
'current':2,
'humidity':3
}

*******  word_counts
Counts how many times each word appeared.
OrderedDict([
('temperature', 42),
('current', 39),
('humidity', 21)
])

 *******document_count
How many training sentences were seen.

*********
What does pickle.dump() save?
When you do pickle.dump(tokenizer, file)
Python saves the entire tokenizer object.

That means it saves:
Tokenizer
│
├── word_index
├── word_counts
├── word_docs
├── document_count
├── configuration
└── everything needed later

It does not save:

❌ sequences
❌ DataFrame
❌ intents.json
❌ responses

Only the tokenizer.
"""

' End of Step 6\n\nAt this point, your data is clean, normalized, and ready for numerical conversion.\n\nThe next step (Step 7) is to:\nConvert the cleaned text into integer sequences using Keras Tokenizer.\nBuild the vocabulary (word_index).\nUnderstand how words are mapped to numbers.\nPrepare the sequences that will later be padded and fed into the LSTM.\n\nThis is the step where the model starts seeing numbers instead of text.\nSentence\n↓\nCurrent temperature today\n↓\nSplit into words\n↓\nCurrent\nTemperature\nToday\n↓\nAssign IDs\n↓\n3\n4\n5\n↓\nSequence\n↓\n\n[3,4,5]\n\nstep 7.1 Create Tokenizer , is an empty object. It knows nothing about your vocabulary.\nStep 7.2 Learn Vocabulary\nNow train the tokenizer on your dataset. What does fit_on_texts() do?\nIt scans every sentence.\nSuppose your dataset is "hi nice"\ntokenizer reades hi -> 1 nice\nexample\n{\n\'hi\':1,\n\'hello\':2,\n\'current\':3,\n\'temperature\':4,\n\'humidity\':5\n} This dictionary is called the Word Index.\n\n\nthe tokenizer learns your entire vocabulary.\n{\n    \'current\': 1,\n    \'temperature\': 2,\n    \'humidity\': 3,\n    \'wind\': 4,\n    \'speed\': 5,\n    \'hi\': 6,\n    \'hello\': 7 ......\n}This dictionary is stored inside the tokenizer.\n\n  *****  word_index\n         Maps each word to an integer.\n         {\n\'temperature\':1,\n\'current\':2,\n\'humidity\':3\n}\n\n*******  word_counts\nCounts how many times each word appeared.\nOrderedDict([\n(\'temperature\', 42),\n(\'current\', 39),\n(\'humidity\', 21)\n])\n\n *******document_count\nHow many training sentences were seen.\n\n*********\nWhat does pickle.dump() save?\nWhen you do pickle.dump(tokenizer, file)\nPython saves the entire tokenizer object.\n\nThat means it saves:\nTokenizer\n│\n├── word_index\n├── word_counts\n├── word_docs\n├── document_count\n├── configuration\n└── everything needed later\n\nIt does not save:\n\n❌ sequences\n❌ DataFrame\n❌ intents.json\n❌ responses\n\nOnly the tokenizer.\n'

In [22]:
# ============================================================
# Step 7: Convert Text into Integer Sequences
# ============================================================

# Import Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer

# Create Tokenizer object
tokenizer = Tokenizer()

# Learn vocabulary from all patterns
tokenizer.fit_on_texts(df["pattern"])

# Display the vocabulary (word -> index)
print("Word Index:\n")
print(tokenizer.word_index)

# Display vocabulary size
print("\nVocabulary Size:", len(tokenizer.word_index))

# Convert each sentence into a sequence of integers
sequences = tokenizer.texts_to_sequences(df["pattern"])

# Display first 10 sentences and their sequences
print("\nFirst 10 Sequences:\n")

for i in range(10):
    print(f"Sentence {i+1}: {df['pattern'][i]}")
    print(f"Sequence  : {sequences[i]}")
    print("-" * 50)

# Example: Convert a new sentence into sequence
test_sentence = ["current temperature today"]

test_sequence = tokenizer.texts_to_sequences(test_sentence)

print("\nExample Sentence:")
print(test_sentence[0])

print("Converted Sequence:")
print(test_sequence)

# Save tokenizer for future prediction
import pickle

with open("../models/tokenizer.pkl", "wb") as file:
    pickle.dump(tokenizer, file)

print("\nTokenizer saved successfully!")

Word Index:

{'in': 1, 'the': 2, 'temperature': 3, 'wind': 4, 'today': 5, 'current': 6, 'me': 7, 'status': 8, 'time': 9, 'weather': 10, 'you': 11, 'what': 12, 'can': 13, 'show': 14, 'is': 15, 'delhi': 16, 'mumbai': 17, 'chennai': 18, 'hyderabad': 19, 'bengaluru': 20, 'kolkata': 21, 'visakhapatnam': 22, 'tell': 23, 'check': 24, 'i': 25, 'need': 26, 'give': 27, 'latest': 28, 'feel': 29, 'like': 30, 'minimum': 31, 'maximum': 32, 'humidity': 33, 'speed': 34, 'direction': 35, 'gust': 36, 'air': 37, 'pressure': 38, 'visibility': 39, 'cloud': 40, 'coverage': 41, 'condition': 42, 'rain': 43, 'snow': 44, 'sunrise': 45, 'sunset': 46, 'timezone': 47, 'good': 48, 'thanks': 49, 'hi': 50, 'hello': 51, 'hey': 52, 'bot': 53, 'chatbot': 54, 'bye': 55, 'see': 56, 'later': 57, 'thank': 58, 'a': 59, 'much': 60, 'help': 61, 'how': 62, 'are': 63, 'your': 64, 'name': 65, 'report': 66, 'blah': 67, 'morning': 68, 'evening': 69, 'there': 70, 'greeting': 71, 'afternoon': 72, 'goodbye': 73, 'take': 74, 'care': 75, 'catch': 76, 'lot': 77, 'appreciated': 78, 'so': 79, 'awesome': 80, 'do': 81, 'command': 82, 'feature': 83, 'supported': 84, 'information': 85, 'who': 86, 'introduce': 87, 'yourself': 88, 'update': 89, 'complete': 90, 'asdf': 91, 'random': 92, 'question': 93}

Vocabulary Size: 93

First 10 Sequences:

Sentence 1: hi
Sequence  : [50]
--------------------------------------------------
Sentence 2: hello
Sequence  : [51]
--------------------------------------------------
Sentence 3: hey
Sequence  : [52]
--------------------------------------------------
Sentence 4: good morning
Sequence  : [48, 68]
--------------------------------------------------
Sentence 5: good evening
Sequence  : [48, 69]
--------------------------------------------------
Sentence 6: hey bot
Sequence  : [52, 53]
--------------------------------------------------
Sentence 7: hello chatbot
Sequence  : [51, 54]
--------------------------------------------------
Sentence 8: hi there
Sequence  : [50, 70]
--------------------------------------------------
Sentence 9: greeting
Sequence  : [71]
--------------------------------------------------
Sentence 10: good afternoon
Sequence  : [48, 72]
--------------------------------------------------

Example Sentence:
current temperature today
Converted Sequence:
[[6, 3, 5]]

Tokenizer saved successfully!

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Find the maximum sentence length
max_length = max(len(sequence) for sequence in sequences)

print("Maximum Sentence Length:", max_length)

# Pad all sequences
padded_sequences = pad_sequences(
    sequences,
    maxlen=max_length,
    padding="post"
)

# Check shape
print("Shape:", padded_sequences.shape)

# View first 5 examples
for i in range(5):
    print("Original :", sequences[i])
    print("Padded   :", padded_sequences[i])
    print("--------------------------------------------------------") # use this both same print("-" * 50)

Maximum Sentence Length: 7
Shape: (341, 7)
Original : [50]
Padded   : [50  0  0  0  0  0  0]
--------------------------------------------------------
Original : [51]
Padded   : [51  0  0  0  0  0  0]
--------------------------------------------------------
Original : [52]
Padded   : [52  0  0  0  0  0  0]
--------------------------------------------------------
Original : [48, 68]
Padded   : [48 68  0  0  0  0  0]
--------------------------------------------------------
Original : [48, 69]
Padded   : [48 69  0  0  0  0  0]
--------------------------------------------------------

In [24]:
"""Until now, your chatbot knows the questions (patterns), but the model still doesn't understand the intent names because they are text.

For example:

Pattern	Tag
Current temperature	current_temperature
Humidity today	humidity
Wind speed	wind_speed

An LSTM cannot predict text labels. It can only predict numbers.

So we convert:

current_temperature → 0
humidity            → 1
wind_speed          → 2
...

This process is called Label Encoding."""

"Until now, your chatbot knows the questions (patterns), but the model still doesn't understand the intent names because they are text.\n\nFor example:\n\nPattern\tTag\nCurrent temperature\tcurrent_temperature\nHumidity today\thumidity\nWind speed\twind_speed\n\nAn LSTM cannot predict text labels. It can only predict numbers.\n\nSo we convert:\n\ncurrent_temperature → 0\nhumidity            → 1\nwind_speed          → 2\n...\n\nThis process is called Label Encoding."

In [25]:
# ============================================================
# Step 9: Label Encoding
# ============================================================

from sklearn.preprocessing import LabelEncoder
import pickle

# Create LabelEncoder
label_encoder = LabelEncoder()

# Learn all intent classes
label_encoder.fit(df["tag"])

# Convert text labels into numbers
encoded_labels = label_encoder.transform(df["tag"])

# Display first 10 encoded labels
print("First 10 Encoded Labels:\n")

for i in range(20):
    print(f"Tag      : {df['tag'][i]}")
    print(f"Encoded  : {encoded_labels[i]}")
    print("-" * 40)

# Display all classes
print("\nIntent Classes:")
print(label_encoder.classes_)

# Display mapping
print("\nLabel Mapping:")

for index, label in enumerate(label_encoder.classes_):
    print(f"{index} -> {label}")

# Save LabelEncoder
with open("../models/label_encoder.pkl", "wb") as file:
    pickle.dump(label_encoder, file)

print("\nLabel Encoder saved successfully!")

First 10 Encoded Labels:

Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : greeting
Encoded  : 5
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : goodbye
Encoded  : 4
----------------------------------------
Tag      : thanks
Encoded  : 16
----------------------------------------
Tag      : thanks
Encoded  : 16
----------------------------------------
Tag      : thanks
Encoded  : 16
----------------------------------------

Intent Classes:
['bot_name' 'cloud_percentage' 'current_temperature'
 'feels_like_temperature' 'goodbye' 'greeting' 'help' 'humidity'
 'local_timezone' 'maximum_temperature' 'minimum_temperature' 'pressure'
 'rain_status' 'snow_status' 'sunrise_time' 'sunset_time' 'thanks'
 'unknown' 'visibility' 'weather_description' 'weather_overview'
 'wind_direction' 'wind_gust' 'wind_speed']

Label Mapping:
0 -> bot_name
1 -> cloud_percentage
2 -> current_temperature
3 -> feels_like_temperature
4 -> goodbye
5 -> greeting
6 -> help
7 -> humidity
8 -> local_timezone
9 -> maximum_temperature
10 -> minimum_temperature
11 -> pressure
12 -> rain_status
13 -> snow_status
14 -> sunrise_time
15 -> sunset_time
16 -> thanks
17 -> unknown
18 -> visibility
19 -> weather_description
20 -> weather_overview
21 -> wind_direction
22 -> wind_gust
23 -> wind_speed

Label Encoder saved successfully!

In [26]:
""" Now your dataset is completely preprocessed.
✅ padded_sequences → Input (X)
✅ encoded_labels → Output (y)

Now we divide the data into training and testing sets
Step 10: Train-Test Split
Goal
Split the dataset into:

Training Data (80%) → Used to train the LSTM.
Testing Data (20%) → Used to evaluate the LSTM on unseen data.

Without stratify
The split is random.
Suppose
Training

Greeting = 43
Weather = 32
Goodbye = 5

Testing

Greeting = 7
Weather = 8
Goodbye = 5

Notice something?
Half of all Goodbye samples ended up in the test set.
The model only learns from 5 Goodbye examples.
This is not ideal.
Even worse, sometimes a rare class may end up entirely in the test set, leaving the model with no examples to learn from.

With stratify=encoded_labels
The function looks at the class labels and tries to maintain the same proportions in both training and testing sets.
Original data:

Label	Percentage
Greeting	50%
Weather	    40%
Goodbye	    10%

If you split 80% train and 20% test:

Training (80 samples)

Label	Count
Greeting	40
Weather  	32
Goodbye	     8

Testing (20 samples)

Label	Count
Greeting	10
Weather	     8
Goodbye	     2

Notice the percentages stay the same.
stratify=encoded_labels
you're telling train_test_split:
"While splitting the data, keep the distribution of these labels the same in the training and testing sets."
"""

' Now your dataset is completely preprocessed.\n✅ padded_sequences → Input (X)\n✅ encoded_labels → Output (y)\n\nNow we divide the data into training and testing sets\nStep 10: Train-Test Split\nGoal\nSplit the dataset into:\n\nTraining Data (80%) → Used to train the LSTM.\nTesting Data (20%) → Used to evaluate the LSTM on unseen data.\n\nWithout stratify\nThe split is random.\nSuppose\nTraining\n\nGreeting = 43\nWeather = 32\nGoodbye = 5\n\nTesting\n\nGreeting = 7\nWeather = 8\nGoodbye = 5\n\nNotice something?\nHalf of all Goodbye samples ended up in the test set.\nThe model only learns from 5 Goodbye examples.\nThis is not ideal.\nEven worse, sometimes a rare class may end up entirely in the test set, leaving the model with no examples to learn from.\n\nWith stratify=encoded_labels\nThe function looks at the class labels and tries to maintain the same proportions in both training and testing sets.\nOriginal data:\n\nLabel\tPercentage\nGreeting\t50%\nWeather\t    40%\nGoodbye\t    10%\n\nIf you split 80% train and 20% test:\n\nTraining (80 samples)\n\nLabel\tCount\nGreeting\t40\nWeather  \t32\nGoodbye\t     8\n\nTesting (20 samples)\n\nLabel\tCount\nGreeting\t10\nWeather\t     8\nGoodbye\t     2\n\nNotice the percentages stay the same.\nstratify=encoded_labels\nyou\'re telling train_test_split:\n"While splitting the data, keep the distribution of these labels the same in the training and testing sets."\n'

In [27]:
# ============================================================
# Step 10: Train-Test Split
# ============================================================

from sklearn.model_selection import train_test_split

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    padded_sequences,
    encoded_labels,
    test_size=0.2,
    random_state=42,
    stratify=encoded_labels
)

# Display shapes
print("Training Features :", X_train.shape)
print("Testing Features  :", X_test.shape)

print()

print("Training Labels   :", y_train.shape)
print("Testing Labels    :", y_test.shape)

# Display one sample
print("\nFirst Training Sequence:")
print(X_train[0])

print("\nEncoded Label:")
print(y_train[0])

print("\nOriginal Intent:")
print(label_encoder.inverse_transform([y_train[0]]))

Training Features : (272, 7)
Testing Features  : (69, 7)

Training Labels   : (272,)
Testing Labels    : (69,)

First Training Sequence:
[44  8  5  0  0  0  0]

Encoded Label:
13

Original Intent:
['snow_status']

In [28]:
import numpy as np

np.save("../models/X_train.npy", X_train)
np.save("../models/X_test.npy", X_test)
np.save("../models/y_train.npy", y_train)
np.save("../models/y_test.npy", y_test)